class Todo {
  bool isComplete;
  String description;
  // This is null when the model is instantiated client-side
  // The id is auto-generated by the backend
  String? id;

  Todo({required this.isComplete, required this.description, this.id});
}
